"""Generate src/ygorl/engine/constants.py from ygopro-core's ocgapi_constants.h.

Usage: uv run python tools/gen_constants.py [--check]

The generated module mirrors every ``#define`` in the header, grouped by the
header's own section comments. ``--check`` exits non-zero if the committed file
is stale (used by the test-suite so a submodule bump cannot silently drift).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "third_party" / "ygopro-core" / "ocgapi_constants.h"
OUTPUT = ROOT / "src" / "ygorl" / "engine" / "constants.py"

_DEFINE = re.compile(r"^#define\s+([A-Z_][A-Z0-9_]*)\s+(.+?)\s*$")
_SECTION = re.compile(r"^/\*\s*(.*?)\s*\*/\s*$")
_CAST = re.compile(r"\(\s*u?int\d+_t\s*\)")
_OCTAL = re.compile(r"\b0([0-7]+)\b")


def _to_python_expr(expr: str) -> str:
    expr = _CAST.sub("", expr)
    expr = _OCTAL.sub(lambda m: "0o" + m.group(1), expr)
    return expr


_DECIMAL = re.compile(r"^[1-9][0-9]*$|^0$")

Section = tuple[str, list[tuple[str, int, bool]]]


def parse_header(text: str) -> list[Section]:
    """Return [(section_title, [(name, value, is_decimal), ...]), ...] in header order."""
    sections: list[Section] = [("", [])]
    env: dict[str, int] = {}
    for raw in text.splitlines():
        line = raw.strip()
        m = _SECTION.match(line)
        if m:
            sections.append((m.group(1), []))
            continue
        m = _DEFINE.match(line)
        if not m:
            continue
        name, expr = m.groups()
        if name.endswith("_H"):  # include guard
            continue
        value = eval(_to_python_expr(expr), {"__builtins__": {}}, env)  # noqa: S307
        env[name] = int(value)
        sections[-1][1].append((name, int(value), bool(_DECIMAL.match(expr))))
    return [(title, items) for title, items in sections if items]


def render(sections: list[Section]) -> str:
    out = [
        '"""Constants mirrored from ygopro-core ocgapi_constants.h.',
        "",
        "GENERATED by tools/gen_constants.py -- do not edit by hand.",
        '"""',
        "",
        "# fmt: off",
    ]
    for title, items in sections:
        out.append("")
        if title:
            out.append(f"# {title}")
        for name, value, is_decimal in items:
            out.append(f"{name} = {value}" if is_decimal else f"{name} = {value:#x}")
    out.append("")
    return "\n".join(out)


def generate() -> str:
    return render(parse_header(HEADER.read_text()))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale; run tools/gen_constants.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
